### ISSUE TITLE
Unable to run rerun via iTerm2 terminal

### ISSUE THREAD

**Issue by greenwookez** [ivpusic/rerun#15]
Hi @ivpusic!
I'm trying to run rerun in iTerm2 terminal and I get a bad file descriptor error.
```
rerun -c rerun.json
git/ivp/rer 21:40:28 ☹[PANI] ▶ Error while reading list of files to listen! bad file descriptor
panic: Error while reading list of files to listen! %s


goroutine 1 [running]:
github.com/ivpusic/golog.(*Logger).Panicf(0xc000166100, {0x12024a8, 0x2f}, {0xc00015de98, 0x1e51ff8, 0x18})
    /Users/greenwookez/go/pkg/mod/github.com/ivpusic/golog@v0.0.0-20170608213328-28640bee649f/logger.go:315 +0x134
main.(*watcher).start(0xc0001261e0)
    /Users/greenwookez/go/pkg/mod/github.com/ivpusic/rerun@v0.0.0-20170331080801-adc8acf1481b/watcher.go:147 +0x2ef
main.main()
    /Users/greenwookez/go/pkg/mod/github.com/ivpusic/rerun@v0.0.0-20170331080801-adc8acf1481b/main.go:51 +0x2af
```

It comes from the [watcher.go](https://github.com/ivpusic/rerun/blob/adc8acf1481b4ec9011e964dd85c68f12609201c/watcher.go#L126-L148) file.

My working directory is smth like root/src/server. It does contain config file for sure. I'am able to run this command via VSCode integrated terminal but I'am not able to do that via iTerm2. iTerm2 has a Full Disk Access in the MacOS privacy settings.

`rerun --verbose -c rerun.json` has the same output is above.

Could you help me with this issue?

**Comment by greenwookez** [comment]
Had to reinstall Mac OS from scratch (instead of migrating from the old Mac with bunch of different configs) and add an `unlim -n <more than 256>`  to the `.zprofile`. Hopefully it will help someone.
